using Content.Client.UserInterface.Controls;
using Content.Shared.Power;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DockingPowerSharer.UI;

[GenerateTypedNameReferences]
public sealed partial class DockingPowerSharerWindow : FancyWindow
{
    public DockingPowerSharerWindow()
    {
        RobustXamlLoader.Load(this);
        LVButton.OnPressed += _ => VoltageChanged?.Invoke(Voltage.Apc);
        MVButton.OnPressed += _ => VoltageChanged?.Invoke(Voltage.Medium);
        HVButton.OnPressed += _ => VoltageChanged?.Invoke(Voltage.High);
    }

    public Action<Voltage>? VoltageChanged;
}

