using Content.Client.UserInterface.Controls;
using Content.Shared.Power;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DockingPowerSharer.UI;

[GenerateTypedNameReferences]
public sealed partial class DockingPowerSharerWindow : FancyWindow
{
    public DockingPowerSharerWindow()
    {
        RobustXamlLoader.Load(this);
        MVDischargeButton.OnPressed += _ => VoltageChanged?.Invoke(Voltage.Medium, true);
        HVDischargeButton.OnPressed += _ => VoltageChanged?.Invoke(Voltage.High, true);
        MVDrawButton.OnPressed += _ => VoltageChanged?.Invoke(Voltage.Medium, false);
        HVDrawButton.OnPressed += _ => VoltageChanged?.Invoke(Voltage.High, false);
    }

    public Action<Voltage, bool>? VoltageChanged;
}

